version: '3.9'
services:
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    ports:
      - ${MEILI_PORT}:${MEILI_PORT}
    environment:
      - MEILI_MASTER_KEY=$MASTER_KEY
      - MEILI_POSTGRES_HOST=$POSTGRES_HOST
      - MEILI_POSTGRES_USER=$POSTGRES_USER
      - MEILI_POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - MEILI_POSTGRES_DB=$POSTGRES_DB
      - MEILI_POSTGRES_PORT=$POSTGRES_PORT
    volumes:
      - meilisearch:/data.ms
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MEILI_PORT}" ]
      interval: 30s
      timeout: 10s
      retries: 5

#  tw-rx-trans:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: tw-rx-trans
#    ports:
#      - ${PORT}:${PORT}
#    depends_on:
#      meilisearch:
#        condition: service_healthy

  cg-osrm-server:
    image: alpine
    container_name: cg-osrm-server
    command: sh -c "cd /data &&
      rm -rf *.osm.pbf &&
      wget https://download.geofabrik.de/africa/congo-brazzaville-latest.osm.pbf -O cg.osm.pbf"
    volumes:
      - osrm:/data

  osrm-extract:
    image: osrm/osrm-backend
    container_name: osrm-extract
    command: osrm-extract -p /opt/car.lua /data/cg.osm.pbf
    volumes:
      - osrm:/data
    depends_on:
      cg-osrm-server:
        condition: service_completed_successfully

  osrm-partition:
    image: osrm/osrm-backend
    container_name: osrm-partition
    command: osrm-partition /data/cg.osm
    volumes:
      - osrm:/data
    depends_on:
      osrm-extract:
        condition: service_completed_successfully

  osrm-customize:
    image: osrm/osrm-backend
    container_name: osrm-customize
    command: osrm-customize /data/cg.osm
    volumes:
      - osrm:/data
    depends_on:
      osrm-partition:
        condition: service_completed_successfully
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    command: "osrm-routed --algorithm mld /data/cg.osrm"
    ports:
      - ${OSRM_PORT}:${OSRM_PORT}
    volumes:
      - osrm:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${OSRM_PORT}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      osrm-customize:
        condition: service_completed_successfully

  db:
    image: postgres:alpine3.18
    container_name: db
    depends_on:
      osrm:
        condition: service_started
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  osrm:
  meilisearch:

