name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' && github.ref_type == 'tag' && github.ref == 'refs/tags/v*.*.*' && replace(github.ref, 'refs/tags/v', '') || github.event_name == 'push' && github.ref_type == 'branch' && github.ref == 'refs/heads/main' && 'latest' || github.event_name == 'push' && github.ref_type == 'branch' && 'v' + github.ref || '' }}-${{ github.head_ref || github.ref_name }}
