name: Create release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name : Install dependancies
        run: npm ci
      - name : Initialize Git user
        run: |
          git config --global user.email "styvelioumba98@gmail.com"
          git config --global user.name "Release workflow"
      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: End message
        run: echo "End of release workflow"